keys:
- &users:
  - &ilian age14zfcwfcs4egqx9w594kxwjgdhz44lmy6p903exntz0p7uha4f52qtkefeg
- &hosts:
  - &legionofnix dsjfalkfsajdjfhbgskvnjkvsj

creation_rules:
- path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
  key_groups:
  - age:
    - *ilian
