[pyprland]
plugins = [
  "scratchpads",
  "magnify",
  "expose",
]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
animation = "fromTop"
class = "kitty-dropterm"
size = "70% 40%"
unfocus = "hide"
excludes = "*"
lazy = true

[scratchpads.volume]
command = "pavucontrol --class volume_sidemenu"
animation = "fromRight"
class = "volume_sidemenu"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true


[scratchpads.music]
command = "kitty --class music -e ncmpcpp"
animation = "fromLeft"
class = "music"
size = "35% 70%"
position = "5% 15%"
unfocus = "hide"
excludes = "*"
lazy = true


[scratchpads.obsidian]
command = "obsidian --class scratchpad"
animation = "fromTop"
class = "scratchpad"
size = "70% 60%"
unfocus = "hide"
excludes = "*"
lazy = true
